id: IC1D16A63
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:06:29+00:00'
last_modified: '2022-06-08T10:46:30.932579+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8751
  title: དབུ་མའི་སྙིང་པོའི་འགྲེལ་པ་རྟོག་གེ་འབར་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CB54:
      image_group_id: I1KG8766
      title: ''
      total_pages: 874
      order: 1
      base_file: CB54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
