id: P009404
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG8751
  title: དབུ་མའི་སྙིང་པོའི་འགྲེལ་པ་རྟོག་གེ་འབར་བ།
  author: ''
  volumes:
    c7146a84a7c7421e95d8870067553fb0:
      image_group_id: I1KG8766
      title: ''
      volume_number: 1
      total_pages: 874
      base_file: v001.txt
